/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import static View.Menu_principal.Tela;

/**
 *
 * @author Felipe
 */
public class Tela_messagem extends javax.swing.JInternalFrame {

//    Controller_Login Con_L = new Controller_Login();
    
    public Tela_messagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        R_senha = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(30, 79, 139));
        setClosable(true);
        setIconifiable(true);
        setTitle("Mensagem");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        R_senha.setBackground(new java.awt.Color(80, 141, 224));
        R_senha.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        R_senha.setForeground(new java.awt.Color(238, 255, 255));
        R_senha.setContentAreaFilled(false);
        R_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_senhaActionPerformed(evt);
            }
        });
        jPanel1.add(R_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 245, 120, 10));

        Login.setBackground(new java.awt.Color(80, 141, 224));
        Login.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Login.setForeground(new java.awt.Color(238, 255, 255));
        Login.setText("Enviar");
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 140, 40));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setText("Mensagem");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setText("Remetente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 290, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 380, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void R_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_senhaActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        //        String pwd = new String(senha.getPassword());
        ////        Integer x = Con_L.logar(usuario.getText(), pwd);
        //
        //        if (null==x) JOptionPane.showMessageDialog(rootPane,"Usuario ou senha Incorreto!");
        //        else switch (x) {
            //            case 1:
            //                JOptionPane.showMessageDialog(rootPane, "Login Efetuado com sucesso!");
            //                dispose();
            ////             Menu_principal menu = new Menu_principal();
            ////             menu.setVisible(true);
            //                break;
            //            case 2:
            //                JOptionPane.showMessageDialog(rootPane, "Login Efetuado com sucesso!");
            //                dispose();
            //                break;
            //            case 3:
            //                JOptionPane.showMessageDialog(rootPane, "Login Efetuado com sucesso!");
            //                dispose();
            //                break;
            //            default:
            //                JOptionPane.showMessageDialog(rootPane,"Usuario ou senha Incorreto!");
            //                break;
            //        }
    }//GEN-LAST:event_LoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JButton R_senha;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
